### ISSUE TITLE
헤더 컴포넌트 구현 

### ISSUE THREAD

**Issue by yeeZinu** [Do-you-like-chicken/Do-You-Like-Chicken-Client#6]
## Description
- 간단한 이미지와 로그인 및 회원가입 버튼 구현

## Todo
- [x] 치킨과 맞는 이미지 찾기
- [x] 헤더 버튼을 통해 로그인 및 회원가입 페이지 라우팅
- [x] 로그인에 성공했다면 해당위치에 유저 닉네임 받아오기

## ETC
- 기타 추가사항
